const messagesEn = {
	text1: "My wallet",
	text2: "Net mortgage pool ETV",
	text3: "Net participants",
	text4: "Net drawing ETVPro",
	text5: "Net harvesting ETVPro",
	text6: "Contract",
	text7: "Inverse entropy",
	text8: "Rule",
	text9: "Audit report",
	text10: "Invitation",
	text11: "Pool",
	text12: "Reverse entropy ETV, earn etvpro",
	text13: "Etvpro redeems at any time",
	text14: "join",
	text15: "Personal",
	text16: "Wallet address",
	text17: "My pledge",
	text18: "See more",
	text19: "My mining",
	text20: "My harvest",
	text21: "To be harvested",
	text22: "Harvest",
	text23: "Harvest address",
	text24: "Harvest quantity",
	text25: "Confirm",
	text26: "Pledge",
	text27: "Enter the number you need to join",
	text28: "Cancel",
	text29: "My account",
	text30: "ETV balance",
	text31: "ETVPro balance",
	text32: "View on Tronscan",
	text33: "Rule",
	text34: "ETV address",
	text35: "ETVPro address",
	text36: "Mining plan",
	text37: "Total supply of etvpro: 2.1 million",
	text38: "50% of the 2.1 million ETV mines will be completed in 3 years, with a monthly decrease of 10% (ETV irreversible)",
	text39: "ETV + etvpro (30% + 70%), 30% of the total mining amount of ETV and etvpro 2.1 million. 3 years, 10% decrease per month",
	text40: "10% liquidity mining (not yet open)",
	text41: "Usdt + etvpro liquidity mining",
	text42: "10% vote for mining",
	text43: "ETV is irreversible and etvpro can be redeemed",
	text44: "Invite friends",
	text45: "Invitation link",
	text46: "Copy link",
	text47: "Statistical records",
	text48: "address",
	text49: "harvest",
	text50: "Coming",
	text51: "Login",
	text52: "Enter your wallet address",
	text53: "Invitation code (only for the first login)",
	text54: "Pledge record",
	text55: "address",
	text56: "pledge",
	text57: "Ore drawing record",
	text58: "Ore drawing",
	text59: "Harvest record",
	text60: "harvest",
	text61: "Harvest success",
	text62: "Successful pledge",
	text63: "Invitation list",
	text64: "Failed to link Wallet",
	text65: "TRX Sorry, your credit is running low",
	text66: "ETV Sorry, your credit is running low",
	text67: "Copy success",
	text68: "Not open yet",
	text69: "Enter the amount you pledge",
	text70: "630,000 zeros have been distributed across the network",
	text71: "The total budget of the pool is 420,000 ETV Pros. Pledged ETV Pros are mined (ETVs irreversible) over 29 months with a 5% monthly drawdown",
	text72: "Pledged ENE Pros (ENE Irreversible) with a total budget of 630,000 ETV Pros in the pool, mined over 60 months with a 5% monthly drawdown",
	text73: "ETV Pros Mobility Mining. ETV Pros has a total budget of 210,000 units, with daily production averaged over 5 years",
	
	text79: "Pledge ene and etvpros",
	text80: "630000, output decreased by 5% in June, long-term return",
	text81: "Dual currency LP liquidity mining",
	text82: "Share 210000 etvpros",
	text83: "Block",
	text84: "Network pledge ENE",
	text85: "Network pledge LP",
	text86: "Pledge address",
	text87: "Pull out",
	text88: "You are about to participate in LP pledge",
	text89: "Partial withdrawal",
	text90: "Withdrawal of all pledged LP and income",
	text91: "Please enter the withdrawal quantity",
	text92: "Please go to Tron wallet for details",
}
export default messagesEn
